version: '3'

services:

  ursa-major-db:
    image: postgres:10.4
    volumes:
      - ursamajordb:/var/lib/postgresql/data/

  ursa-major-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
      - ~/.pe-shared/aurora-ursamajor:/src/:ro
      - ~/.pe-shared/ursamajor-fornax:/dest/
    ports:
      - "8005:8005"
    depends_on:
      - ursa-major-db

volumes:
  ursamajordb:
