version: '3'

services:

  ursa-major-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example

  ursa-major-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - ursa-major-db
